Repository QwenLM/qwen-code, pull requests merged in 2025-09, with the labels that each got.

#521 Terminal Bench Integration Test
  .github/workflows/ci.yml
  .github/workflows/terminal-bench.yml
  integration-tests/terminal-bench/ci-tasks/.gitignore
  integration-tests/terminal-bench/ci-tasks/hello-world/Dockerfile
  integration-tests/terminal-bench/ci-tasks/hello-world/docker-compose.yaml
  integration-tests/terminal-bench/ci-tasks/hello-world/run-tests.sh
  integration-tests/terminal-bench/ci-tasks/hello-world/solution.sh
  integration-tests/terminal-bench/ci-tasks/hello-world/task.yaml
  integration-tests/terminal-bench/ci-tasks/hello-world/tests/run-uv-pytest.sh
  integration-tests/terminal-bench/ci-tasks/hello-world/tests/setup-uv-pytest.sh
  integration-tests/terminal-bench/ci-tasks/hello-world/tests/test_outputs.py
  integration-tests/terminal-bench/ci-tasks/swe-bench-astropy-1/Dockerfile
  integration-tests/terminal-bench/ci-tasks/swe-bench-astropy-1/docker-compose.yaml
  integration-tests/terminal-bench/ci-tasks/swe-bench-astropy-1/run-tests.sh
  integration-tests/terminal-bench/ci-tasks/swe-bench-astropy-1/solution.sh
  integration-tests/terminal-bench/ci-tasks/swe-bench-astropy-1/task.yaml
  integration-tests/terminal-bench/qwen-code-setup.sh.j2
  integration-tests/terminal-bench/qwen_code.py
  integration-tests/terminal-bench/terminal-bench.test.ts
  integration-tests/vitest.config.ts
  package.json
Labels: bug, status/need-information

#50 refactor(cli): update OpenAI API key prompt with Bailian URL
  packages/cli/src/ui/components/OpenAIKeyPrompt.tsx
Labels: bug, status/need-information

#610 Add `skipLoopDetection` Configuration Option
  docs/cli/configuration.md
  packages/cli/src/config/config.ts
  packages/cli/src/config/settingsSchema.ts
  packages/core/src/config/config.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
Labels: enhancement

#638 fix: subagent system improvements and UI fixes
  docs/subagents.md
  packages/cli/src/ui/App.tsx
  packages/cli/src/ui/components/HistoryItemDisplay.tsx
  packages/cli/src/ui/components/messages/ToolConfirmationMessage.tsx
  packages/cli/src/ui/components/subagents/create/AgentCreationWizard.tsx
  packages/cli/src/ui/components/subagents/manage/AgentSelectionStep.tsx
  packages/cli/src/ui/components/subagents/manage/AgentsManagerDialog.tsx
  packages/cli/src/ui/components/subagents/runtime/AgentExecutionDisplay.tsx
  packages/cli/src/ui/hooks/useGeminiStream.ts
  packages/core/src/core/client.test.ts
  packages/core/src/core/client.ts
  packages/core/src/subagents/subagent-manager.test.ts
  packages/core/src/subagents/subagent-manager.ts
  packages/core/src/subagents/types.ts
Labels: enhancement, status/need-information

#693 🐛 Fix: Resolve Markdown list display issues on Windows
  packages/cli/src/ui/utils/MarkdownDisplay.test.tsx
  packages/cli/src/ui/utils/MarkdownDisplay.tsx
  packages/cli/src/ui/utils/__snapshots__/MarkdownDisplay.test.tsx.snap
Labels: bug, status/need-retesting, priority/P1
